// Generated by LiveScript 1.2.0
var Padnews, pad, pub, express, app, x$, server, y$, io;
Padnews = require('padnews');
pad = new Padnews('sgyfCRGiBZC', 'g0v');
pub = './public';
express = require('express');
app = express();
x$ = app;
x$.use(app.router);
x$.set('view engine', 'jade');
x$.get('/', function(req, res){
  return res.render('index', {
    news: pad.news
  });
});
x$.get('/json', function(req, res){
  var x$;
  x$ = res;
  x$.setHeader('Access-Control-Allow-Origin', '*');
  x$.json({
    total: pad.news.length,
    latest: pad.news.slice(pad.news.length - 42)
  });
  return x$;
});
server = require('http').Server(app);
y$ = io = require('socket.io').listen(server);
y$.set('log level', 1);
y$.sockets.on('connection', function(socket){
  return socket.emit('msg', 'http://g0v.today');
});
pad.run(10000, function(event, data, i, diff){
  var patch;
  if (event === 'ready') {
    return server.listen(process.env.PORT) || 5000;
  } else {
    patch = {
      op: event === 'create' ? 'add' : 'replace',
      path: "/" + i,
      value: data
    };
    return io.sockets.emit('patch', patch);
  }
});