// Generated by LiveScript 1.2.0
var Padnews, pad, pub, express, app, x$, server, io, later;
Padnews = require('padnews');
pad = new Padnews('sgyfCRGiBZC', 'g0v');
pub = './public';
express = require('express');
app = express();
x$ = app;
x$.use(app.router);
x$.set('view engine', 'jade');
x$.get('/', function(req, res){
  return res.render('index', {
    news: pad.news
  });
});
x$.get('/json', function(req, res){
  return res.json(pad.news);
});
server = require('http').Server(app);
io = require('socket.io').listen(server);
later = function(){};
setTimeout(function(){
  return later = function(event, data, i, diff){
    var patch;
    patch = {
      op: event === 'create' ? 'add' : 'replace',
      path: "/" + i,
      value: data
    };
    io.sockets.emit('patch', patch);
  };
}, 30000);
pad.run(10000, function(event, data, i, diff){
  return later(event, data, i, diff);
});
io.sockets.on('connection', function(socket){
  return socket.emit('msg', 'http://g0v.today');
});
server.listen(process.env.PORT) || 8888;